import type {
  Trainer,
  Course,
  Organization,
  TrainerDashboardKPIs,
  OrganizationDashboardKPIs,
  UpcomingSession,
  ActivityItem,
  MonthlyRevenuePoint,
  MonthlySpendingPoint,
  UpcomingTraining,
} from "@/types";

export const trainers: Trainer[] = [
  {
    id: "t1",
    name: "Sophie Martin",
    bio: "Développeuse senior fullstack avec 12 ans d'expérience. Spécialisée React, Node.js et architecture cloud.",
    specialties: ["React", "Node.js", "TypeScript", "AWS"],
    city: "Paris",
    hourlyRate: 120,
    rating: 4.9,
    reviewCount: 87,
    avatar: "/placeholder-avatar.png",
  },
  {
    id: "t2",
    name: "Marc Dubois",
    bio: "Expert data science et machine learning. Ancien lead data chez un grand groupe bancaire.",
    specialties: ["Python", "Machine Learning", "TensorFlow", "SQL"],
    city: "Lyon",
    hourlyRate: 135,
    rating: 4.8,
    reviewCount: 64,
    avatar: "/placeholder-avatar.png",
  },
  {
    id: "t3",
    name: "Amina Benali",
    bio: "UX/UI Designer passionnée par l'accessibilité et le design system. 8 ans d'expérience en agence et freelance.",
    specialties: ["Figma", "UX Research", "Design System", "Accessibilité"],
    city: "Bordeaux",
    hourlyRate: 95,
    rating: 4.7,
    reviewCount: 52,
    avatar: "/placeholder-avatar.png",
  },
  {
    id: "t4",
    name: "Thomas Leroy",
    bio: "DevOps engineer et formateur certifié Kubernetes. Accompagne les équipes dans leur transition cloud native.",
    specialties: ["Docker", "Kubernetes", "CI/CD", "Terraform"],
    city: "Nantes",
    hourlyRate: 140,
    rating: 4.9,
    reviewCount: 41,
    avatar: "/placeholder-avatar.png",
  },
  {
    id: "t5",
    name: "Claire Fontaine",
    bio: "Consultante marketing digital spécialisée en growth hacking et SEO technique.",
    specialties: ["SEO", "Google Ads", "Analytics", "Growth Hacking"],
    city: "Toulouse",
    hourlyRate: 85,
    rating: 4.6,
    reviewCount: 73,
    avatar: "/placeholder-avatar.png",
  },
  {
    id: "t6",
    name: "Julien Moreau",
    bio: "Coach agile et formateur en management. Certifié SAFe et Scrum Master. Accompagne les transformations organisationnelles.",
    specialties: ["Scrum", "SAFe", "Management Agile", "Leadership"],
    city: "Lille",
    hourlyRate: 110,
    rating: 4.8,
    reviewCount: 96,
    avatar: "/placeholder-avatar.png",
  },
];

export const courses: Course[] = [
  {
    id: "c1",
    title: "React Avancé — Patterns et Performance",
    description:
      "Maîtrisez les patterns avancés de React : hooks personnalisés, render props, compound components et optimisation des performances.",
    price: 890,
    duration: "3 jours",
    category: "DEVELOPMENT",
    status: "PUBLISHED",
    trainerId: "t1",
    trainerName: "Sophie Martin",
    enrollmentCount: 124,
    image: "/placeholder-course.png",
  },
  {
    id: "c2",
    title: "Machine Learning pour les entreprises",
    description:
      "Introduction pratique au ML pour décideurs et développeurs. De la donnée au modèle déployé en production.",
    price: 1200,
    duration: "5 jours",
    category: "DATA",
    status: "PUBLISHED",
    trainerId: "t2",
    trainerName: "Marc Dubois",
    enrollmentCount: 89,
    image: "/placeholder-course.png",
  },
  {
    id: "c3",
    title: "Design System — Créer et maintenir",
    description:
      "Apprenez à concevoir, documenter et faire vivre un design system pérenne avec Figma et Storybook.",
    price: 650,
    duration: "2 jours",
    category: "DESIGN",
    status: "PUBLISHED",
    trainerId: "t3",
    trainerName: "Amina Benali",
    enrollmentCount: 67,
    image: "/placeholder-course.png",
  },
  {
    id: "c4",
    title: "Kubernetes en production",
    description:
      "Déployer, monitorer et scaler vos applications sur Kubernetes. Inclut Helm, Istio et observabilité.",
    price: 1500,
    duration: "4 jours",
    category: "DEVOPS",
    status: "PUBLISHED",
    trainerId: "t4",
    trainerName: "Thomas Leroy",
    enrollmentCount: 45,
    image: "/placeholder-course.png",
  },
  {
    id: "c5",
    title: "SEO technique pour développeurs",
    description:
      "Comprendre et implémenter le SEO technique : performance web, données structurées, Core Web Vitals.",
    price: 490,
    duration: "2 jours",
    category: "MARKETING",
    status: "PUBLISHED",
    trainerId: "t5",
    trainerName: "Claire Fontaine",
    enrollmentCount: 156,
    image: "/placeholder-course.png",
  },
  {
    id: "c6",
    title: "Leadership agile pour managers",
    description:
      "Transformez votre management avec les principes agiles. Facilitation, feedback, et organisation apprenante.",
    price: 780,
    duration: "3 jours",
    category: "MANAGEMENT",
    status: "PUBLISHED",
    trainerId: "t6",
    trainerName: "Julien Moreau",
    enrollmentCount: 203,
    image: "/placeholder-course.png",
  },
  {
    id: "c7",
    title: "Next.js 16 — Server Components et App Router",
    description:
      "Découvrez les dernières fonctionnalités de Next.js : Server Components, streaming, server actions et déploiement edge.",
    price: 950,
    duration: "3 jours",
    category: "DEVELOPMENT",
    status: "DRAFT",
    trainerId: "t1",
    trainerName: "Sophie Martin",
    enrollmentCount: 0,
    image: "/placeholder-course.png",
  },
  {
    id: "c8",
    title: "Architecture microservices avec Node.js",
    description:
      "Concevoir et implémenter une architecture microservices robuste avec Node.js, RabbitMQ et Docker.",
    price: 1100,
    duration: "4 jours",
    category: "DEVELOPMENT",
    status: "DRAFT",
    trainerId: "t1",
    trainerName: "Sophie Martin",
    enrollmentCount: 0,
    image: "/placeholder-course.png",
  },
];

export const organizations: Organization[] = [
  {
    id: "o1",
    name: "TechCorp Formation",
    description:
      "Organisme de formation spécialisé dans les métiers du numérique. Certifié Qualiopi.",
    logo: "/placeholder-logo.png",
    city: "Paris",
    employeeCount: 45,
  },
  {
    id: "o2",
    name: "FormaPro Institute",
    description:
      "Centre de formation continue pour les entreprises. Plus de 200 formations au catalogue.",
    logo: "/placeholder-logo.png",
    city: "Lyon",
    employeeCount: 120,
  },
  {
    id: "o3",
    name: "Digital Academy",
    description:
      "Accélérateur de compétences digitales pour les équipes en transformation.",
    logo: "/placeholder-logo.png",
    city: "Bordeaux",
    employeeCount: 30,
  },
];

const upcomingSessions: UpcomingSession[] = [
  {
    id: "s1",
    courseTitle: "React Avancé — Patterns et Performance",
    organizationName: "TechCorp Formation",
    date: "2026-03-24",
    startTime: "09:00",
    endTime: "17:00",
    location: "Paris",
    type: "ONSITE",
  },
  {
    id: "s2",
    courseTitle: "React Avancé — Patterns et Performance",
    organizationName: "FormaPro Institute",
    date: "2026-03-28",
    startTime: "09:30",
    endTime: "17:30",
    location: "En ligne",
    type: "REMOTE",
  },
  {
    id: "s3",
    courseTitle: "Next.js 16 — Server Components et App Router",
    organizationName: "Digital Academy",
    date: "2026-04-02",
    startTime: "09:00",
    endTime: "17:00",
    location: "Bordeaux",
    type: "ONSITE",
  },
  {
    id: "s4",
    courseTitle: "Architecture microservices avec Node.js",
    organizationName: "TechCorp Formation",
    date: "2026-04-14",
    startTime: "10:00",
    endTime: "18:00",
    location: "En ligne",
    type: "REMOTE",
  },
];

const recentActivity: ActivityItem[] = [
  {
    id: "a1",
    type: "ENROLLMENT",
    message: "3 nouveaux inscrits à React Avancé — Patterns et Performance",
    timestamp: "2026-03-16T14:30:00",
  },
  {
    id: "a2",
    type: "REVIEW",
    message: "Nouvel avis 5/5 de Pierre Durand sur React Avancé",
    timestamp: "2026-03-16T10:15:00",
  },
  {
    id: "a3",
    type: "PAYMENT",
    message: "Paiement de 2 670 \u20AC re\u00E7u de TechCorp Formation",
    timestamp: "2026-03-15T16:45:00",
  },
  {
    id: "a4",
    type: "ENROLLMENT",
    message: "1 nouvel inscrit \u00E0 React Avanc\u00E9 via la marketplace",
    timestamp: "2026-03-15T09:20:00",
  },
  {
    id: "a5",
    type: "COURSE_PUBLISHED",
    message: "Votre formation Next.js 16 est en attente de validation",
    timestamp: "2026-03-14T11:00:00",
  },
  {
    id: "a6",
    type: "REVIEW",
    message: "Nouvel avis 4/5 de Marie Lefèvre sur React Avancé",
    timestamp: "2026-03-13T17:30:00",
  },
  {
    id: "a7",
    type: "PAYMENT",
    message: "Paiement de 890 \u20AC re\u00E7u via la marketplace",
    timestamp: "2026-03-12T14:00:00",
  },
];

const monthlyRevenueData: MonthlyRevenuePoint[] = [
  { month: "Jan", revenue: 3200, previousYear: 2800 },
  { month: "Fév", revenue: 4100, previousYear: 3200 },
  { month: "Mar", revenue: 3800, previousYear: 3500 },
  { month: "Avr", revenue: 5200, previousYear: 4100 },
  { month: "Mai", revenue: 4900, previousYear: 4300 },
  { month: "Jun", revenue: 5100, previousYear: 4600 },
  { month: "Jul", revenue: 4800, previousYear: 3900 },
  { month: "Aoû", revenue: 5600, previousYear: 4200 },
  { month: "Sep", revenue: 4200, previousYear: 3800 },
  { month: "Oct", revenue: 3900, previousYear: 3600 },
  { month: "Nov", revenue: 5100, previousYear: 4500 },
  { month: "Déc", revenue: 4350, previousYear: 3800 },
];

export const trainerDashboardKPIs: TrainerDashboardKPIs = {
  totalRevenue: 47250,
  activeCourses: 4,
  totalStudents: 312,
  averageRating: 4.8,
  monthlyRevenue: [3200, 4100, 3800, 5200, 4900, 5100, 4800, 5600, 4200, 3900, 5100, 4350],
  revenueTrend: 12.5,
  studentsTrend: 8.2,
  ratingTrend: 2.1,
  coursesTrend: 0,
  monthlyRevenueData,
  upcomingSessions,
  recentActivity,
};

const orgMonthlySpendingData: MonthlySpendingPoint[] = [
  { month: "Jan", spending: 8500, previousYear: 7200 },
  { month: "Fév", spending: 12000, previousYear: 9800 },
  { month: "Mar", spending: 9800, previousYear: 8500 },
  { month: "Avr", spending: 11200, previousYear: 9200 },
  { month: "Mai", spending: 10500, previousYear: 8800 },
  { month: "Jun", spending: 14200, previousYear: 11500 },
  { month: "Jul", spending: 13100, previousYear: 10200 },
  { month: "Aoû", spending: 9800, previousYear: 7600 },
  { month: "Sep", spending: 11500, previousYear: 9900 },
  { month: "Oct", spending: 12800, previousYear: 10800 },
  { month: "Nov", spending: 10200, previousYear: 9100 },
  { month: "Déc", spending: 14800, previousYear: 12400 },
];

const orgUpcomingTrainings: UpcomingTraining[] = [
  {
    id: "ot1",
    courseTitle: "React Avancé — Patterns et Performance",
    trainerName: "Sophie Martin",
    date: "2026-03-24",
    startTime: "09:00",
    endTime: "17:00",
    location: "Paris",
    type: "ONSITE",
    employeeCount: 8,
  },
  {
    id: "ot2",
    courseTitle: "Machine Learning pour les entreprises",
    trainerName: "Marc Dubois",
    date: "2026-03-31",
    startTime: "09:30",
    endTime: "17:30",
    location: "En ligne",
    type: "REMOTE",
    employeeCount: 12,
  },
  {
    id: "ot3",
    courseTitle: "Kubernetes en production",
    trainerName: "Thomas Leroy",
    date: "2026-04-07",
    startTime: "09:00",
    endTime: "17:00",
    location: "Paris",
    type: "ONSITE",
    employeeCount: 6,
  },
  {
    id: "ot4",
    courseTitle: "Leadership agile pour managers",
    trainerName: "Julien Moreau",
    date: "2026-04-14",
    startTime: "10:00",
    endTime: "18:00",
    location: "En ligne",
    type: "REMOTE",
    employeeCount: 15,
  },
];

const orgRecentActivity: ActivityItem[] = [
  {
    id: "oa1",
    type: "TRAINER_HIRED",
    message: "Sophie Martin a accepté la mission React Avancé",
    timestamp: "2026-03-16T15:00:00",
  },
  {
    id: "oa2",
    type: "TRAINING_COMPLETED",
    message: "Formation SEO technique terminée — 12 employés certifiés",
    timestamp: "2026-03-15T17:00:00",
  },
  {
    id: "oa3",
    type: "PAYMENT",
    message: "Facture de 4 450 \u20AC réglée pour Machine Learning",
    timestamp: "2026-03-15T10:30:00",
  },
  {
    id: "oa4",
    type: "ENROLLMENT",
    message: "5 employés inscrits à Kubernetes en production",
    timestamp: "2026-03-14T14:20:00",
  },
  {
    id: "oa5",
    type: "TRAINER_HIRED",
    message: "Thomas Leroy a accepté la mission Kubernetes",
    timestamp: "2026-03-13T11:45:00",
  },
  {
    id: "oa6",
    type: "TRAINING_COMPLETED",
    message: "Formation Design System terminée — 8 employés formés",
    timestamp: "2026-03-12T17:00:00",
  },
  {
    id: "oa7",
    type: "PAYMENT",
    message: "Facture de 7 800 \u20AC réglée pour Leadership agile",
    timestamp: "2026-03-11T09:15:00",
  },
];

export const organizationDashboardKPIs: OrganizationDashboardKPIs = {
  totalSpent: 128400,
  activeTrainers: 12,
  coursesCompleted: 34,
  employeesTrained: 186,
  monthlySpending: [8500, 12000, 9800, 11200, 10500, 14200, 13100, 9800, 11500, 12800, 10200, 14800],
  spentTrend: 15.3,
  trainersTrend: 9.1,
  coursesTrend: 6.3,
  employeesTrend: 12.8,
  monthlySpendingData: orgMonthlySpendingData,
  upcomingTrainings: orgUpcomingTrainings,
  recentActivity: orgRecentActivity,
};
